<template><h1 id="插件配置" tabindex="-1"><a class="header-anchor" href="#插件配置" aria-hidden="true">#</a> 插件配置</h1>
<ul>
<li>
<p>appId</p>
<blockquote>
<p>必需,leanCloud中的appId</p>
</blockquote>
</li>
<li>
<p>appKey</p>
<blockquote>
<p>必需，leanCloud中的appKey</p>
</blockquote>
</li>
</ul>
<p>​</p>
<ul>
<li>
<p>masterKey</p>
<blockquote>
<p>必需，leanCloud中的masterKey</p>
</blockquote>
</li>
<li>
<p>avatarPath</p>
<blockquote>
<p><code>可选</code>说说头像url</p>
</blockquote>
</li>
<li>
<p>registerPath</p>
<blockquote>
<p><code>可选</code>自定义插件默认提供的注册页面路由，请在前面加上<code>/</code></p>
</blockquote>
</li>
<li>
<p>onlyAdministrator</p>
<blockquote>
<p><code>可选</code>是否运行其他注册的用户发布说说，true表示只有管理员可以发布</p>
</blockquote>
</li>
</ul>
<h2 id="组件使用" tabindex="-1"><a class="header-anchor" href="#组件使用" aria-hidden="true">#</a> 组件使用</h2>
<p><RouterLink to="/plugin/coze/component.html">组件使用</RouterLink></p>
</template>
